ALTER TABLE groups        ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE membership    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE expenses      ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE settlements   ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE expense_share ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
